name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Vagy amit használsz

    - name: Install dependencies (dev)
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt  # dev requirements telepítése (Flask + pytest + pylint)

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    # Itt tudod később hozzáadni a deploy lépéseket, ha akarod
