name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Választhatsz más operációs rendszert is, ha szükséges

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Állítsd be a kívánt Python verziót

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Feltételezve, hogy van requirements.txt fájl

    - name: Run tests with unittest
      run: |
        python -m unittest discover -s tests  # A teszt mappa futtatása, ha van
